twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        build_version: "1.0.0"
        deployed_status: false
        env_languages:
            - code: "ro"
              label: Romanian
            - code: "en"
              label: "english"
    form_themes:
      [
        "Form/Type/checkBoxUpdate.html.twig",
        # "Form/Type/baseTemplate.html.twig",
      ]
when@test:
    twig:
        strict_variables: true
